### ISSUE TITLE
Exception details

### ISSUE THREAD

**Issue by Judithlourde** [opensourceBIM/python-mvdxml#17]
Hi, I tried the python-mvdxml it works well. I have one question about the result 
ConceptRoot: IfcBuilding
Concept: Spatial Decomposition
EXCEPTION: 'rule' object has no attribute 'parent'
What is the meaning of EXCEPTION? 
Thanks for the answer:)

**Comment by aothms** [comment]
I ran into that as well recently. See this commit https://github.com/opensourceBIM/python-mvdxml/commit/00e9f56c7d04f889ad9340af82f124ef5ba36efe that should fix it

**Comment by Judithlourde** [comment]
Hi Thomas,
Could you please explain the result when i validate this mvdXml file with ifc file MinimalWindow.ifc

<Views>
    <ModelView uuid="a3713e64-6251-4569-b8c6-934fa6acfb25" name="DEMO" applicableSchema="IFC4">
      <ExchangeRequirements>
        <ExchangeRequirement uuid="139cd9af-7874-4c62-aab8-9ca39dc25dd2" name="Example" applicability="both" />
      </ExchangeRequirements>
      <Roots>
        <ConceptRoot uuid="f4170e8d-5041-40fb-82d2-7f12f8c7329b" name="" applicableRootEntity="IfcBuildingElementProxy">
          <Concepts>
            <Concept uuid="f19755da-4ca0-4d90-9b9f-627b8a3c6e9c" name="SingleValueProperty" override="false">
              <Definitions>
                <Definition>
                  <Body><![CDATA[The property of fire rating should be provided.]]></Body>
                </Definition>
              </Definitions>
              <Template ref="7aaad17c-20a0-4117-8abc-050d0c67e6ec" />
              <Requirements>
                <Requirement applicability="import" requirement="mandatory" exchangeRequirement="139cd9af-7874-4c62-aab8-9ca39dc25dd2" />
                <Requirement applicability="export" requirement="mandatory" exchangeRequirement="139cd9af-7874-4c62-aab8-9ca39dc25dd2" />
              </Requirements>
              <Rules>
                <TemplateRule Parameters="PropertyName[Value]='FireRating'" />
              </Rules>
            </Concept>
          </Concepts>
        </ConceptRoot>
        <ConceptRoot uuid="8101d3e8-afe0-448c-b803-f80874ab63a5" name="" applicableRootEntity="IfcWindow">
          <Concepts>
            <Concept uuid="6ca5d3a3-ae77-49a3-9012-96180d68810b" name="SingleValueProperty" override="false">
              <Definitions>
                <Definition>
                  <Body><![CDATA[The property of fire rating should be provided.]]></Body>
                </Definition>
              </Definitions>
              <Template ref="7aaad17c-20a0-4117-8abc-050d0c67e6ec" />
              <Requirements>
                <Requirement applicability="import" requirement="mandatory" exchangeRequirement="139cd9af-7874-4c62-aab8-9ca39dc25dd2" />
                <Requirement applicability="export" requirement="mandatory" exchangeRequirement="139cd9af-7874-4c62-aab8-9ca39dc25dd2" />
              </Requirements>
              <Rules>
                <TemplateRule Parameters="PropertyName='FireRating'" />
              </Rules>
            </Concept>
          </Concepts>
        </ConceptRoot>
      </Roots>
    </ModelView>
  </Views>
  
Getting this result:

ConceptRoot: IfcDoor
Concept: SingleValueProperty
0 out of 0 instances failed the check
---------------------------------
---------------------------------
ConceptRoot: IfcWindow
Concept: SingleValueProperty
[VALID] #13=IfcWindow('270QYpgSXDE99ViyemAGdV',#2,'Window #1',$,$,$,$,$,$,$,$,$,$)
0 out of 1 instances failed the check
---------------------------------
---------------------------------

RESULTS OVERVIEW
Total number of tests: 2
Total number of executed tests: 2
Total number of failed tests: 0
  
In the minimalWindow file there is one window do not have the fireRating property but the result shows it is valid.

**Comment by Judithlourde** [comment]
MvdXml file:
<Views>
    <ModelView uuid="a3713e64-6251-4569-b8c6-934fa6acfb25" name="DEMO" applicableSchema="IFC4">
      <ExchangeRequirements>
        <ExchangeRequirement uuid="139cd9af-7874-4c62-aab8-9ca39dc25dd2" name="Example" applicability="both" />
      </ExchangeRequirements>
      <Roots>
        <ConceptRoot uuid="f4170e8d-5041-40fb-82d2-7f12f8c7329b" name="" applicableRootEntity="IfcDoor">
          <Concepts>
            <Concept uuid="f19755da-4ca0-4d90-9b9f-627b8a3c6e9c" name="SingleValueProperty" override="false">
              <Definitions>
                <Definition>
                  <Body><![CDATA[The property of fire rating should be provided.]]></Body>
                </Definition>
              </Definitions>
              <Template ref="7aaad17c-20a0-4117-8abc-050d0c67e6ec" />
              <Requirements>
                <Requirement applicability="import" requirement="mandatory" exchangeRequirement="139cd9af-7874-4c62-aab8-9ca39dc25dd2" />
                <Requirement applicability="export" requirement="mandatory" exchangeRequirement="139cd9af-7874-4c62-aab8-9ca39dc25dd2" />
              </Requirements>
              <Rules>
                <TemplateRule Parameters="PropertyName[Value]='FireRating'" />
              </Rules>
            </Concept>
          </Concepts>
        </ConceptRoot>
        <ConceptRoot uuid="8101d3e8-afe0-448c-b803-f80874ab63a5" name="" applicableRootEntity="IfcWindow">
          <Concepts>
            <Concept uuid="6ca5d3a3-ae77-49a3-9012-96180d68810b" name="SingleValueProperty" override="false">
              <Definitions>
                <Definition>
                  <Body><![CDATA[The property of fire rating should be provided.]]></Body>
                </Definition>
              </Definitions>
              <Template ref="7aaad17c-20a0-4117-8abc-050d0c67e6ec" />
              <Requirements>
                <Requirement applicability="import" requirement="mandatory" exchangeRequirement="139cd9af-7874-4c62-aab8-9ca39dc25dd2" />
                <Requirement applicability="export" requirement="mandatory" exchangeRequirement="139cd9af-7874-4c62-aab8-9ca39dc25dd2" />
              </Requirements>
              <Rules>
                <TemplateRule Parameters="PropertyName='FireRating'" />
              </Rules>
            </Concept>
          </Concepts>
        </ConceptRoot>
      </Roots>
    </ModelView>
  </Views>

**Comment by Judithlourde** [comment]
Github does not accept mvdxml extensions.
[FireRatingDemo.txt](https://github.com/opensourceBIM/python-mvdxml/files/14433857/FireRatingDemo.txt)

**Comment by aothms** [comment]
> MinimalWindow.ifc

Can you share that?

**Comment by Judithlourde** [comment]
Sure!
[MinimalWindow.txt](https://github.com/opensourceBIM/python-mvdxml/files/14434446/MinimalWindow.txt)

**Comment by Judithlourde** [comment]
Apologies for the confusion earlier. I've reviewed the mvdXML file and found an error, which I've now corrected. I appreciate your patience and understanding. Thank you! The corrected mvdXML file is here.
[FireRatingDemo (3).txt](https://github.com/opensourceBIM/python-mvdxml/files/14635302/FireRatingDemo.3.txt)
