### ISSUE TITLE
saving spreadsheet_export true and the folder non-existing

### ISSUE THREAD

**Issue by kavehAlahdin** [opensourceBIM/python-mvdxml#7]
In the `get_data() `method, if the spreadsheet_export is True , but the folder `spreadsheet_output `in the python file path not exists, it throws an exception.

```
Error:
         [Errno 2] No such file or directory: 'spreadsheet_output/output_non_filtered.xlsx'
Traceback (most recent call last):
  File "craneplanningIfc.py", line 144, in <module>
    craneplnIfc.getRelevantEntities()
  File "craneplanningIfc.py", line 62, in getRelevantEntities
    for a in all_data:
TypeError: 'NoneType' object is not iterable
```
After creating that folder manually in the path, it works fine.

**Comment by johltn** [comment]
This has been fixed in [502b845](https://github.com/opensourceBIM/python-mvdxml/commit/502b8454ff3b89c473b0670cceb31bdad70861fc)
