### ISSUE TITLE
importError: cannot import ifcopenshell_wrapper

### ISSUE THREAD

**Issue by ESiham** [opensourceBIM/python-mvdxml#9]
I tried running this with python 3.9, but I  got this error:
ImportError: cannot import name 'ifcopenshell_wrapper' from partially initialized module 'ifcopenshell' (most likely due to o circular import).
Have any suggestions about this error ?

**Comment by johltn** [comment]
I've just tested it on a 3.9 anaconda environment and it worked fine. 

I suggest you to : 
- Download the right python version of ifcopenshell-python there https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-39-v0.6.0-f2b645b-win64.zip and extract the ifcopenshell folder
- Clone the python-mvdxml repo inside the ifcopenshell folder and rename it `mvd`
- Try to run the getting started code example from outside the ifcopenshell folder

**Comment by ESiham** [comment]
Thank you so much @johltn for your response! Also, my apologies for the late reply. 
I tried to do what you suggested and it works perfectly.
